<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Downloading QR Code - <?= htmlspecialchars($room->name) ?></title>
    <link rel="icon" type="image/png" href="<?= base_url('assets-tamplate/img/logo-primaya.png'); ?>">
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <!-- Library QR Code JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
    <style>
        :root {
            --navy: #1a2744;
            --green: #16a34a;
            --bg-gray: #f8fafc;
            --text-dark: #0f172a;
            --text-muted: #475569;
        }

        body {
            font-family: 'Plus Jakarta Sans', sans-serif;
            background-color: var(--bg-gray);
            color: var(--text-dark);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: 0;
            padding: 20px;
        }

        .loader-container {
            text-align: center;
            background: #ffffff;
            padding: 40px;
            border-radius: 16px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.05);
            max-width: 400px;
            width: 100%;
        }

        .spinner {
            border: 4px solid rgba(26, 39, 68, 0.1);
            width: 50px;
            height: 50px;
            border-radius: 50%;
            border-left-color: var(--green);
            animation: spin 1s linear infinite;
            margin: 0 auto 20px auto;
        }

        @keyframes spin {
            0% {
                transform: rotate(0deg);
            }
            100% {
                transform: rotate(360deg);
            }
        }

        h2 {
            font-size: 18px;
            color: var(--navy);
            margin-bottom: 8px;
            font-weight: 700;
        }

        p {
            font-size: 14px;
            color: var(--text-muted);
            margin: 0;
        }

        /* Hidden container for QR code generation */
        #qrcode {
            display: none;
        }
    </style>
</head>
<body>

    <div class="loader-container">
        <div class="spinner"></div>
        <h2>Mengunduh QR Code</h2>
        <p><?= htmlspecialchars($room->name) ?></p>
    </div>

    <!-- Hidden element to generate QR -->
    <div id="qrcode"></div>

    <script>
        // Target URL survey
        var surveyUrl = '<?= base_url("survey/form/" . $room->slug); ?>';

        // Render QR Code (hidden, size 500x500 for high quality printable image)
        var qrcode = new QRCode(document.getElementById("qrcode"), {
            text: surveyUrl,
            width: 500,
            height: 500,
            colorDark: "#000000", // Standard black for best scan compatibility
            colorLight: "#ffffff",
            correctLevel: QRCode.CorrectLevel.H
        });

        // Wait for generation
        window.addEventListener('load', function() {
            setTimeout(function() {
                // Find canvas generated by qrcode.js
                var canvas = document.querySelector("#qrcode canvas");
                if (canvas) {
                    var imgUrl = canvas.toDataURL("image/png");
                    
                    // Create download link
                    var downloadLink = document.createElement("a");
                    downloadLink.href = imgUrl;
                    downloadLink.download = "qr-<?= $room->slug; ?>.png";
                    
                    // Trigger download
                    document.body.appendChild(downloadLink);
                    downloadLink.click();
                    document.body.removeChild(downloadLink);
                } else {
                    // Fallback to img tag if canvas is not used/found
                    var img = document.querySelector("#qrcode img");
                    if (img && img.src) {
                        var downloadLink = document.createElement("a");
                        downloadLink.href = img.src;
                        downloadLink.download = "qr-<?= $room->slug; ?>.png";
                        document.body.appendChild(downloadLink);
                        downloadLink.click();
                        document.body.removeChild(downloadLink);
                    }
                }

                // Close window after a short delay
                setTimeout(function() {
                    window.close();
                }, 500);
            }, 300);
        });
    </script>

</body>
</html>
